GoogleContainerTools/container-structure-test

- release_cloudbuild.yaml
> Finish release automation.

- cloudbuild.yaml
- release_cloudbuild.yaml
> also push image to tag when we release

- release_cloudbuild.yaml
> Push new structure test images to latest tag when releasing

- types/v1/structure.go
- types/v2/structure.go
Fixed the error in the struct tag because the `FileContentTests` could not be run.
> fix FileContentTests not running.

- drivers/docker_driver.go
This removes the intermediate container created in the file tests when retrieving the image filesystem.
Fixes #39
> Remove intermediate container in file tests

- .travis.yml
- BUILD.bazel
- tests/structure_test_tests.sh
Also add a test for the image.
This should fix #59
> Make the structure test binary build with "pure".

- README.md
Fix some errors related to bazel.
> fix bazel-related document

- cmd/test.go
> Allow .yml file extension

- README.md
- cloudbuild.yaml
- release_cloudbuild.yaml
This adds support for releasing a binary for OS X!
Fixes #67
> Support cross compilation

- pkg/types/v2/command.go
> Fix Error Message when Command is empty

- pkg/types/v1/file_existence.go
- pkg/types/v2/file_existence.go
- tests/debian_failure_test.yaml
- tests/debian_test.yaml
> Fix ShouldFileExists in File Existence Test and add a test

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/GoogleCloudPlatform/runtimes-common/ctc_lib/container_tool_command_base.go
- vendor/github.com/GoogleCloudPlatform/runtimes-common/ctc_lib/ctc_lib.go
- vendor/github.com/spf13/cobra/args.go
- vendor/github.com/spf13/cobra/bash_completions.go
- vendor/github.com/spf13/cobra/cobra.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/pflag/bytes.go
- vendor/github.com/spf13/pflag/count.go
- vendor/github.com/spf13/pflag/duration_slice.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/golangflag.go
- vendor/github.com/spf13/pflag/int16.go
- vendor/github.com/spf13/pflag/string_array.go
- vendor/github.com/spf13/pflag/string_slice.go
This fixes the nil pointer deref. 
Fixes #135
> Bump runtimes-common.

- .gcloudignore
cc @nkubala this lets you use gcloud locally.
> Ignore broken symlinks.

- README.md
Just fixing the example to add the test command 😄
> Fix missing test command in tar driver example

- pkg/types/v1/file_existence.go
- pkg/types/v2/file_existence.go
> Don't check file permissions if file doesn't exist

- README.md
> Make clear in readme that schema version is required in yaml

- README.md
Signed-off-by: Aisuko <urakiny@gmail.com>
Hi, Thank you for developing the amazing project. I'm learning the skaffold concept about `test`. So, I'm here and according to the context, I believe the code below needs to reformat.
> Reformat example code

- README.md
Hi,
I found this information by accident in an issue of yours, but I think it is crucial to understand how the setup function works and how it can be used properly.
Greets,
Domi
> Enhanced command tests documentation

- README.md
According to https://github.com/GoogleContainerTools/container-structure-test/issues/215
> Improved documentation examples

- pkg/types/v1/file_existence.go
- pkg/types/v2/file_existence.go
modified version of https://github.com/GoogleContainerTools/container-structure-test/pull/243
cc @dgageot
> Don't check properties of a file that doesn't exist

- deploy/cloudbuild.yaml
- deploy/release_cloudbuild.yaml
I commented the upload and I'm running `deploy/cloudbuild.yaml` now.
> revert changes to name, since in GCB this isn't cosmetic

- cmd/container-structure-test/app/cmd/test.go
- cmd/container-structure-test/app/cmd/test/util.go
- go.mod
- go.sum
- pkg/config/options.go
- tests/structure_test_tests.sh
@loosebazooka this is one of the changes we'd like to land to reduce churn for the `structure_test` rule downstream.
> feat: support --image-from-oci-layout

- go.mod
- go.sum
This fixes https://github.com/advisories/GHSA-v95c-p5hm-xq8f
> Update runc to v1.0.3

- go.mod
- go.sum
Picks up https://github.com/GoogleContainerTools/container-diff/pull/395 fixes #183
> chore: update container-diff dependency

- bazel/container_structure_test.bzl
> Add bazel platform support
