- release.sh
run `./release.sh <commit_sha>` to copy the binary built at that commit to the `latest` directory in the GCS bucket.
cc @dlorenc
> add release script

- types/v2/structure.go
If the image driver isn't created successfully, the test can't run, so halt immediately.
Fixes #12
> Halt test if driver not created successfully

- BUILD.bazel
- README.md
- drivers/driver.go
- structure_test.go
This will allow users to pass the `-pull` flag to force a pull of an image before running tests.
Fixes #17
> Add option to pull image before running tests

- README.md
- drivers/docker_driver.go
- drivers/driver.go
- drivers/tar_driver.go
- structure_test.go
- types.go
- types/v1/structure.go
- types/v2/structure.go
This changes the default behavior to remove the intermediate artifact for each test after creating. Users can pass the `-save` flag to keep the intermediate container or tar archive around after the test run.
Fixes #16
> Remove intermediate container/tar archive after creating

- BUILD.bazel
- structure_test.go
This will make the tests error if someone passes an invalid YAML, instead of silently ignore it.
> Switch to go-yaml so we can use strict parsing.

- BUILD.bazel
- drivers/docker_driver.go
- drivers/driver.go
- drivers/tar_driver.go
- structure_test.go
- types.go
- types/unversioned/types.go
- types/v1/structure.go
- types/v2/structure.go
This is a precursor change that will allow us to add drivers that accept different parameters than `image` and `save`.
Also, fix a small bug where the `TarDriver` was ignoring the `save` boolean parameter.
> Refactor driver interface to accept variable args

- BUILD.bazel
- structure_test.go
This reverts commit 5a1465d8e4142e56aa6224a5ccd02834f942804b.
Looks like something with parsing is broken with this change, let's revert until we figure out why it doesn't work.
> Revert "Switch to go-yaml so we can use strict parsing. (#26)"

- BUILD.bazel
- structure_test.go
- types.go
- types/v1/command.go
- types/v1/file_content.go
- types/v1/file_existence.go
- types/v1/licenses.go
- types/v1/structure.go
- types/v2/command.go
- types/v2/file_content.go
- types/v2/file_existence.go
- types/v2/licenses.go
- types/v2/metadata.go
- types/v2/structure.go
It looks like the big difference is that go-yaml defaults to fully
lower-cased field names, not camel-cased.
> Switch to strict yaml parsing.

- BUILD.bazel
- drivers/BUILD.bazel
- drivers/docker_driver.go
- drivers/driver.go
- drivers/host_driver.go
- drivers/tar_driver.go
- structure_test.go
- types/unversioned/types.go
- types/v1/command.go
- types/v1/structure.go
- types/v2/command.go
- utils/utils.go
This PR implements a test driver for running directly on the host machine. This will allow us to create sandboxes based off of bazel "flattened" images and run the test binary directly inside them, in cases where it's not possible to use the existing drivers. In general, users should be discouraged from using this driver, as it can have potentially harmful side effects on a host machine (e.g. running a command test or setting an env var that has destructive effects).
> Add host driver

- types/v2/structure.go
The actual and expected values were backwards which was really confusing. Also renamed a variable for clarity.
> Fix metadata test output order

- types/v2/structure.go
This prevents some nil pointer derefs in the case of some test failures.
This should fix #58
> Switch errorf to fatalf.

- Gopkg.lock
- Gopkg.toml
- drivers/tar_driver.go
- vendor/github.com/GoogleCloudPlatform/container-diff/cmd/root.go
- vendor/github.com/GoogleCloudPlatform/container-diff/pkg/util/cloud_prepper.go
- vendor/github.com/GoogleCloudPlatform/container-diff/pkg/util/daemon_prepper.go
- vendor/github.com/GoogleCloudPlatform/container-diff/pkg/util/image_prep_utils.go
- vendor/github.com/GoogleCloudPlatform/container-diff/pkg/util/tar_prepper.go
Go ahead and check the local daemon when running the tar driver. Even though we should probably be using the docker driver if you have an image locally, we shouldn't stop users from using the tar driver if they want to.
Fixes #71 and #72 (along with https://github.com/GoogleCloudPlatform/container-diff/pull/202 and https://github.com/GoogleCloudPlatform/container-diff/pull/203)
> Check for image in local daemon when running tests with tar driver

- BUILD.bazel
- WORKSPACE
- config.json
This adds the docker-credential-gcr tool into the container-structure-test binary and image, which can be used to authenticate against private registries. 
Fixes #83 
Fixes #84
> Add support for running tests on private images

- BUILD.bazel
- cmd/test.go
- pkg/output/BUILD.bazel
- pkg/output/output.go
- pkg/output/output_utils.go
- pkg/types/BUILD.bazel
- pkg/types/types.go
- pkg/types/unversioned/types.go
- pkg/types/v1/BUILD.bazel
- pkg/types/v1/structure.go
- pkg/types/v2/BUILD.bazel
- pkg/types/v2/structure.go
This change makes the results of the tests stream out to the console as the tests are run, instead of waiting for all tests to finish running before outputting. This changes the signatures for all test-related methods to take in an `OutWriter`, and put the responsibility on the test methods themselves to write out their results.
> Stream test results as they are run

- pkg/types/v2/structure.go
This call got left out when I rewrote the framework a few weeks ago.
Fixes #97
> Run metadata tests

- pkg/types/v2/metadata.go
- pkg/types/v2/structure.go
Also fix a panic that happened when an empty string was passed in the `Cmd` field.
Fixes #96
> Add validation for metadata test

- cmd/root.go
- cmd/test.go
- pkg/output/output.go
- pkg/types/v2/metadata.go
- pkg/types/v2/structure.go
* don't run tests if config isn't parsed correctly
* validate metadata test before running
* fix output format and use buffers to write strings
* remove extraneous log statements
> Various run and output fixes

- pkg/drivers/docker_driver.go
- pkg/drivers/driver.go
- pkg/drivers/host_driver.go
- pkg/drivers/tar_driver.go
- pkg/types/v1/command.go
- pkg/types/v1/structure.go
- pkg/types/v2/command.go
- pkg/types/v2/file_existence.go
- pkg/types/v2/metadata.go
- pkg/types/v2/structure.go
- pkg/utils/utils.go
This adds support for performing inline environment variable substitutions directly in the config, for all test types. Global environment variables will now be set in all tests, and substitutions will be performed on all fields provided in the test config before running the tests. For example, this is now a valid test config:
```
schemaVersion: "2.0.0"
globalEnvVars:
- key: "FOO"
value: "/usr/bin"
commandTests:
- name: Path env var
command: "echo"
args: ["$PATH"]
expectedOutput: [".*/usr/bin.*"]
fileExistenceTests:
- name: Python with env vars
path: "$FOO/python2.7"
shouldExist: true
```
Fixes #107 
Fixes #98
> Set global env vars in all tests, and support substitutions

- README.md
- pkg/types/v2/metadata.go
- tests/Dockerfile.metadata
- tests/debian_metadata_test.yaml
There are valid unix environment variables that create regexes that don't match themselves in Golang (i.e. `a\"b`). It's not really useful to use regexes to check for environment variable values anyway, so removing this in favor of direct string comparison.
> Don't allow regexes when checking env/labels in metadata test

- pkg/drivers/docker_driver.go
This removes the intermediate container created to set environment variables.
re-fixes #39
> Remove intermediate env var container

- pkg/types/v2/metadata.go
This was causing a panic if the entrypoint lengths were not the same.
> Fail immediately if entrypoint lengths do not match

- pkg/types/v2/command.go
- pkg/types/v2/file_content.go
- pkg/types/v2/file_existence.go
- pkg/types/v2/metadata.go
- pkg/types/v2/structure.go
Before, we only logged an error when validation (or anything involved in the test setup) failed, causing some runs with failed tests to exit with code 0, breaking some CI flows. This will return a failed test result whenever anything in the test run process fails.
Fixes #146
> Fail tests properly when validation fails

- cmd/test.go
- pkg/types/v1/file_existence.go
- pkg/types/v1/structure.go
- pkg/types/v2/file_existence.go
- pkg/types/v2/structure.go
- tests/debian_failure_test.yaml
Previously, we were using `yaml.UnmarshalStrict` to do the unmarshalling of the configs, but since we were ignoring the error, this was failing silently all over the place. With this change, configs are now strictly validated, and tests will fail to run if any parsing errors occur.
In order to do this, I needed to add the `SchemaVersion` to the top level struct so this could be parsed out correctly. Also, renamed a few things to make them more clear if they're surfaced to the user.
Should fix #146
> Strict unmarshalling for configs

- cmd/test.go
- pkg/output/output.go
This fixes an issue where a test success from one config files would overwrite the failure of another config file, causing the entire test run to be reported as a success.
Also adds a few output modifications.
Fixes #146
> Fail entire test run if one config file fails

- pkg/drivers/tar_driver.go
This happens when the driver is `tar` and an tar file is passed as the
image.
> Fix tar-format image not being properly prepared.

- README.md
The current example run in the readme is specifying some legacy arguments. 
This updates to reflect the correct arguments in the latest release.
> Update example run

- README.md
- pkg/types/v2/file_existence.go
- tests/debian_test.yaml
Adds two new fields `uid` and `gid` to a FileExistenceTest to ensure
that a file or directory is owned by a specific user or group.
Both fields are optional.
> Check ownership of a file or directory

- README.md
- pkg/types/v2/file_existence.go
- tests/debian_test.yaml
Ref #63 
Adds an additional field to File Execution tests; `isExecutableBy`. This checks a given file (or folder) has executable permissions for a specified user type:
- `owner`
- `group`
- `other`
- `all` (Passes if _any_ executable bit is set)
Optional field that can be ommitted.
This follows similar convention to that of serverspec's `be_executable` assertion.
> Check files executable bit against a specified user group

- pkg/types/v2/command.go
- pkg/types/v2/metadata.go
Makes it quicker to spot what is actually incorrect in these tests.
> Log actual values in error message.

- pkg/drivers/host_driver.go
- pkg/types/unversioned/types.go
- pkg/types/v2/metadata.go
- tests/Dockerfile.metadata
- tests/debian_metadata_test.yaml
Fixes https://github.com/GoogleContainerTools/container-structure-test/issues/145
As mentioned in the above issue, this feature was removed in PR https://github.com/GoogleContainerTools/container-structure-test/pull/137. This is an attempt to add the feature back while supporting cases where regex is not desired. It will be off by default and can be used by specifying an optional `isRegex` flag for each key/value pair.
> Adds regex support for env/label metadata tests

- README.md
In fileContentTests documentation, the expectedContents example contains double backslash but it seems it only needs one.
> Fix characters escaping in expectedContents expression

- cmd/container-structure-test/app/cmd/test.go
- pkg/drivers/host_driver.go
- pkg/types/unversioned/types.go
- tests/structure_test_tests.sh
The host driver is very useful for validating image metadata in the case
where docker daemon is not available and producing a fat tarball with
"docker save" would be too costly.  The host driver should allow us to
implement very fast metadata tests for bazel-built containers.
The host driver was broken, because --image command line flag had been
marked required even though host driver uses the --metadata flag (and
rejects the --image flag).
Add end-to-end test coverage for the tar and host drivers.
> Fix broken host driver, add tests for tar and host drivers

- cmd/container-structure-test/app/cmd/test.go
- cmd/container-structure-test/app/cmd/test_test.go
Add helper function to split image name into registry/image and tag pieces incl. test.
Use this function instead of simply splitting the image string.
fixes #193 
fixes #194
> Fix pulling image with registry:port or digest

- README.md
- cmd/container-structure-test/app/cmd/test.go
- pkg/config/options.go
- pkg/drivers/docker_driver.go
- pkg/drivers/driver.go
By default no specific runtime is selected.
It allows to select `runsc` to run using gVisor if present.
```shell
container-structure-test test \
--driver docker --runtime runsc \
--image gcr.io/registry/image:latest \
--config config.yaml
```
> Allow to specify docker runtime to use

- README.md
Hi everyone 👋 
As explained here: https://github.com/GoogleContainerTools/container-structure-test/issues/212. 
The `schemaVersion` can't be `v2.0.0` but need to be `2.0.0` in order to parse the file.
Thanks for the feedback 🙂
> [FIX] SchemaVersion

- README.md
Referring the code:
```
type FileExistenceTest struct {
Name           string `yaml:"name"`           // name of test
Path           string `yaml:"path"`           // file to check existence of
ShouldExist    bool   `yaml:"shouldExist"`    // whether or not the file should exist
Permissions    string `yaml:"permissions"`    // expected Unix permission string of the file, e.g. drwxrwxrwx
Uid            int    `yaml:"uid"`            // ID of the owner of the file
Gid            int    `yaml:"gid"`            // ID of the group of the file
IsExecutableBy string `yaml:"isExecutableBy"` // name of group that file should be executable by
}
```
I think the proposed change is more accurate
> file existence test docs: replace access by owner

- README.md
- pkg/types/v2/metadata.go
- tests/debian_metadata_test.yaml
This PR adds support for `unexposedPorts` and `unmountedVolumes` to `metadataTests` as specified in #171.
Metadata tests and documentation have been updated accordingly.
> Add unexposedPorts and unmountedVolumes to metadata tests

- cmd/container-structure-test/app/cmd/test/util.go
- pkg/output/output.go
- pkg/types/unversioned/types.go
- pkg/types/v1/command.go
- pkg/types/v2/command.go
Hi 👋 
First of all, thanks for your work!
I love *container-structure-test* 😄 
This PR adds a `Duration` field in `TestResult` as well as `SummaryObject` so we can measure each test duration and print a total duration in the report.
Fixes #139
> Add test duration

- README.md
in my opinion, there was little documentation on the optional flags. so i didn't know about `--test-output` and some others for a while. i think they'd suit being in the readme itself!
> add in flags to README

- cmd/container-structure-test/app/cmd/test/util.go
Since both JSON and YAML are supported, mentioning only JSON is really confusing.
> Fix the error message for missing schema versions

- README.md
After wasting a hour to find out how to test for the existence of labels and not for the content. I finally found #172 which implemented this.
> Added isRegex as example in MetaData test

- deploy/cloudbuild.yaml
- deploy/release_cloudbuild.yaml
cc @dlorenc 
I was able to produce `arm64` binaries on my ubuntu VM with `GOARCH=arm64 make cross`
> Produce linux/arm64 binaries for use in container_test

- README.md
- cmd/container-structure-test/app/cmd/test.go
- cmd/container-structure-test/app/cmd/test/util.go
- pkg/config/options.go
- pkg/output/output.go
- pkg/output/output_test.go
- pkg/types/unversioned/types.go
* deprecated `json` flag option
* added new flag option `output`
* added warning when using `test-report` as JSON is default and text not supported
* added JUnit support for `test-report`
* added tests for FinalResults
closes #207
> :sparkles: Add new output format JUnit

- .travis.yml
- deploy/cloudbuild.yaml
- deploy/release_cloudbuild.yaml
- tests/ppc64le/ubuntu_20_04_failure_test.yaml
- tests/ppc64le/ubuntu_20_04_metadata_test.yaml
- tests/ppc64le/ubuntu_20_04_test.yaml
- tests/s390x/ubuntu_20_04_failure_test.yaml
- tests/s390x/ubuntu_20_04_metadata_test.yaml
- tests/s390x/ubuntu_20_04_test.yaml
The binary can be cross-compiled for s390x and ppc64le. All tests in Travis are passed.
Similar to what @mattmoor is done for arm64 -> https://github.com/GoogleContainerTools/container-structure-test/pull/266
> Produce linux/s390x and linux/ppc64le binaries to use in container_test

- README.md
- pkg/drivers/docker_driver.go
- pkg/drivers/host_driver.go
- pkg/drivers/tar_driver.go
- pkg/types/unversioned/types.go
- pkg/types/v2/metadata.go
Hello there! Thanks for this cool tool!
The issue #80 mentions some metadata Image fields that are not available.
This PR implements the support for the field "user" which defines the default user of a container.
This is really useful when you want to check that an image is not launching container as root by default :)
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> Add support for the "user" metadata. Related to #80.

- pkg/drivers/host_driver.go
- pkg/drivers/tar_driver.go
@midnightconman @charlyx this is a recreation of https://github.com/GoogleContainerTools/container-structure-test/pull/247 with integration tests running on it!
> Use os.Lstat over os.Stat

- README.md
- pkg/types/v2/metadata.go
- tests/amd64/ubuntu_20_04_metadata_test.yaml
- tests/arm64/ubuntu_20_04_metadata_test.yaml
- tests/ppc64le/ubuntu_20_04_metadata_test.yaml
- tests/s390x/ubuntu_20_04_metadata_test.yaml
This will check the metadata whether the specified env variables really aren't present.
Fixes #281
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
> Add test for unbound env variables

- README.md
relates to #286
```
$ brew install container-structure-test
...
🍺  /usr/local/Cellar/container-structure-test/1.10.0: 6 files, 12.8MB
```
```
$ container-structure-test
container-structure-test provides a powerful framework to validate
the structure of a container image.
These tests can be used to check the output of commands in an image,
as well as verify metadata and contents of the filesystem.
```
cc @wndhydrnt @nkubala
> docs: add homebrew install guide

- README.md
- pkg/types/v2/metadata.go
- tests/amd64/ubuntu_20_04_metadata_test.yaml
- tests/arm64/ubuntu_20_04_metadata_test.yaml
- tests/ppc64le/ubuntu_20_04_metadata_test.yaml
- tests/s390x/ubuntu_20_04_metadata_test.yaml
To be consistent with other test, e.g. commandTests.
> Refactor Metadata EnvVars and UnboundEnvVars on metadataTest

- README.md
I forget to change document on previous pull request.
https://github.com/GoogleContainerTools/container-structure-test/pull/314
> Change env to envVars on metadataTest

- pkg/output/output.go
- pkg/output/output_test.go
- pkg/types/unversioned/types.go
- tests/amd64/ubuntu_20_04_failure_test.yaml
- tests/amd64/ubuntu_20_04_test.yaml
- tests/structure_test_tests.sh
Fixes #273 & #304
I added two new types to handle the JUnit specific marshaling. This probably can be implemented a bit better rather than inline structs + new types just for making encoding/xml happy.
tests pass. Had to make a tweak to tests/structure_test_tests.sh get the script to run correctly. Could use a pair of eyes to make sure its kosher 👀 
```bash
$ make test
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags " -X github.com/GoogleContainerTools/container-structure-test/pkg/version.version=v1.11.0 -X github.com/GoogleContainerTools/container-structure-test/pkg/version.buildDate=2022-09-10T23:12:32Z " -o out/container-structure-test-linux-amd64 github.com/GoogleContainerTools/container-structure-test/cmd/container-structure-test
cp ./out/container-structure-test-linux-amd64 …
```
> fix JUnit report format

- bazel/container_structure_test.bzl
This causes us to hit https://github.com/GoogleContainerTools/container-structure-test/issues/183 in most cases. See https://buildkite.com/bazel/bcr-presubmit/builds/1247#0187e4cc-44e1-4e21-89a7-08e71f612bfc as an example.
We'll need to fix this in order to properly support Windows, but that is already broken for other reasons.
> fix(bazel): don't give absolute path for images

- MODULE.bazel
- bazel/container_structure_test.bzl
- bazel/test/WORKSPACE.bazel
- defs.bzl
- repositories.bzl
See: https://github.com/bazel-contrib/rules_oci/issues/384
> refactor: remove yq dependency

- README.md
- cmd/container-structure-test/app/cmd/test.go
- go.mod
- go.sum
- pkg/config/options.go
- pkg/drivers/docker_driver.go
- pkg/drivers/driver.go
- tests/structure_test_tests.sh
- for images under test, pass the new --platform flag to pull the
corresponding image if it is multi-platform capable
- test execution via CreateContainerOptions passes in platform. If
unset, will default to linux/$GOARCH
Related: #373 
This required a small enhancement from go-dockerclient via https://github.com/fsouza/go-dockerclient/pull/1017. Updated go.mod was grabbed from the latest commit.
TODO:
> feat: --platform flag

- Makefile
Hello `container-structure-test` maintainers!
My company has moved most of its Engineering team to M1 machines, we still use `container-structure-test` in our `amd64` build pipelines but we would also like to be able to run it more easily while developing locally. I have tested adding the `darwin/arm64` target to the Makefile and it appears to be functioning as expected. Looking through your ci yamls, I believe the repo is already set up to handle this addition seamlessly but please let me know if I missed something. I purposely did not follow the release procedure since that seems like a separate PR/core maintainer concern but I'm happy to adjust if requested.
Thanks for your help!
```shell
make test
cp ./out/container-structure-test-darwin-arm64 out/container-structure-test …
```
> Add support for darwin/arm64

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yaml
This should autopopulate releases with binaries, I don't know how this affects the bazel X.X.1 release shenanigans tough
After the first release of a container we need to make the package public.
> Use goreleaser to autopopulate releases

- bazel/container_structure_test.bzl
- cmd/container-structure-test/app/cmd/test.go
For some reason daemon.Write does not return error when docker daemon clearly indicates failure. This change does not fix daemon.Write but prints the result returned by the daemon and does an additional probe to see if image got loaded successfully before proceeding to test.
> fix: unmask loading errors

- .github/workflows/integration-tests.yml
- bazel/container_structure_test.bzl
- cmd/container-structure-test/app/cmd/test.go
- pkg/config/options.go
This fixes issue where when two image containing same `org.opencontainers.image.ref.name` annotation lead to random failures when running simultaneously.  This introduces a new flag to ignore those annotations which is the default for bazel rules.
> fix: add option to ignore ref annotation

- MODULE.bazel
- bazel/toolchains_repo.bzl
There is no binary published for linux/i386, causing failures in some situations when depending on this module.
Fixes https://github.com/GoogleContainerTools/container-structure-test/issues/409
> Remove linux_i386 from Bazel setup

- repositories.bzl
I've been trying to use `container-structure-test` via Bazel on a Darwin ARM64 machine without Rosetta and kept having the error:
```log
==================== Test output for //:structure:
/private/var/tmp/_bazel_drb/90c1aedef04b4dc3f5392ec26da69ab7/sandbox/darwin-sandbox/321/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/structure.sh.runfiles/_main/structure.sh: line 24
: /private/var/tmp/_bazel_drb/90c1aedef04b4dc3f5392ec26da69ab7/sandbox/darwin-sandbox/321/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/structure.sh.runfiles/container_structure_test~~extension~structu
re_test_st_darwin_arm64/structure_test: Bad CPU type in executable
================================================================================
```
Double checking with:
```log
❯ file …
```
> Enable Darwin ARM64 binaries to be used in Bazel

- .github/workflows/integration-tests.yml
- MODULE.bazel
- MODULE.bazel.lock
- repositories.bzl
checksum extraction script:
```
#!/usr/bin/env bash
while read line
do 
IFS=\  read -r checksum artifact <<< $line
art_hash=$(echo $checksum | xxd -r -p | base64)
art_os=${artifact#"container-structure-test-"}
echo "\"$art_os\": \"sha256-${art_hash}\""
done
```
usage: `cat checksums.txt | <./this-script.sh>` where `checksums.txt` is in the github release (generated by goreleaser)
I'm not fully sure about the MODULE.bazel update -- is there no tool to do this automatically?
> chore: update checksums

- pkg/output/output.go
- pkg/output/output_test.go
- pkg/types/unversioned/types.go
Add the contents of stdout and stderr when creating junit test results.
I'm not sure if there is a formal definition of junit, so I followed https://github.com/testmoapp/junitxml and it seems to work in CircleCI.
(I couldn't see a pull request template, I'll be happy to add anything necessary)
> Add stdout and stderr to JUnit test results

- pkg/drivers/docker_driver.go
The docker driver always creates a new container + image in [`Setup`](https://github.com/GoogleContainerTools/container-structure-test/blob/9894abb7becc658a3952e1bc249437fc479bc067/pkg/drivers/docker_driver.go#L100C6-L100C9), which for large images causes a long delay during [`Destroy` ](https://github.com/GoogleContainerTools/container-structure-test/blob/9894abb7becc658a3952e1bc249437fc479bc067/pkg/drivers/docker_driver.go#L94). For my image with a simple test that checks for the exit code, skipping the new image creation when there is no env saves 3min of execution time:
Before: `container-structure-test -v debug test -c  -i   0.03s user 0.03s system 0% cpu 3:26.83 total`
After: `container-structure-test -v debug test -c  -i   0.03s user 0.01s system 0% cpu 14.933 total`
> Skip creating new image if env is empty

- README.md
Only the first 'amd64' was replaced with 'arm64' in the command. 
Currently the command fails.
> fix: change amd64 to arm64 in installation command for mac
